name: Notify Slack on PR Opened

on:
  pull_request:
    types:
      - opened

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "A new pull request has been opened: <'$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/pull/$GITHUB_REF'>"}' \
          $SLACK_WEBHOOK_URL